// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.tangled.repo.forkSync
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ForkSync<'a> {
    /// Branch to sync
    #[serde(borrow)]
    pub branch: jacquard_common::CowStr<'a>,
    /// DID of the fork owner
    #[serde(borrow)]
    pub did: jacquard_common::types::string::Did<'a>,
    /// Name of the forked repository
    #[serde(borrow)]
    pub name: jacquard_common::CowStr<'a>,
    /// AT-URI of the source repository
    #[serde(borrow)]
    pub source: jacquard_common::types::string::AtUri<'a>,
}

pub mod fork_sync_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
        type Source;
        type Name;
        type Branch;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
        type Source = Unset;
        type Name = Unset;
        type Branch = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Did = Set<members::did>;
        type Source = S::Source;
        type Name = S::Name;
        type Branch = S::Branch;
    }
    ///State transition - sets the `source` field to Set
    pub struct SetSource<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSource<S> {}
    impl<S: State> State for SetSource<S> {
        type Did = S::Did;
        type Source = Set<members::source>;
        type Name = S::Name;
        type Branch = S::Branch;
    }
    ///State transition - sets the `name` field to Set
    pub struct SetName<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetName<S> {}
    impl<S: State> State for SetName<S> {
        type Did = S::Did;
        type Source = S::Source;
        type Name = Set<members::name>;
        type Branch = S::Branch;
    }
    ///State transition - sets the `branch` field to Set
    pub struct SetBranch<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetBranch<S> {}
    impl<S: State> State for SetBranch<S> {
        type Did = S::Did;
        type Source = S::Source;
        type Name = S::Name;
        type Branch = Set<members::branch>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
        ///Marker type for the `source` field
        pub struct source(());
        ///Marker type for the `name` field
        pub struct name(());
        ///Marker type for the `branch` field
        pub struct branch(());
    }
}

/// Builder for constructing an instance of this type
pub struct ForkSyncBuilder<'a, S: fork_sync_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> ForkSync<'a> {
    /// Create a new builder for this type
    pub fn new() -> ForkSyncBuilder<'a, fork_sync_state::Empty> {
        ForkSyncBuilder::new()
    }
}

impl<'a> ForkSyncBuilder<'a, fork_sync_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ForkSyncBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ForkSyncBuilder<'a, S>
where
    S: fork_sync_state::State,
    S::Branch: fork_sync_state::IsUnset,
{
    /// Set the `branch` field (required)
    pub fn branch(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> ForkSyncBuilder<'a, fork_sync_state::SetBranch<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        ForkSyncBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ForkSyncBuilder<'a, S>
where
    S: fork_sync_state::State,
    S::Did: fork_sync_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> ForkSyncBuilder<'a, fork_sync_state::SetDid<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        ForkSyncBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ForkSyncBuilder<'a, S>
where
    S: fork_sync_state::State,
    S::Name: fork_sync_state::IsUnset,
{
    /// Set the `name` field (required)
    pub fn name(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> ForkSyncBuilder<'a, fork_sync_state::SetName<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        ForkSyncBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ForkSyncBuilder<'a, S>
where
    S: fork_sync_state::State,
    S::Source: fork_sync_state::IsUnset,
{
    /// Set the `source` field (required)
    pub fn source(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> ForkSyncBuilder<'a, fork_sync_state::SetSource<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        ForkSyncBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> ForkSyncBuilder<'a, S>
where
    S: fork_sync_state::State,
    S::Did: fork_sync_state::IsSet,
    S::Source: fork_sync_state::IsSet,
    S::Name: fork_sync_state::IsSet,
    S::Branch: fork_sync_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> ForkSync<'a> {
        ForkSync {
            branch: self.__unsafe_private_named.0.unwrap(),
            did: self.__unsafe_private_named.1.unwrap(),
            name: self.__unsafe_private_named.2.unwrap(),
            source: self.__unsafe_private_named.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> ForkSync<'a> {
        ForkSync {
            branch: self.__unsafe_private_named.0.unwrap(),
            did: self.__unsafe_private_named.1.unwrap(),
            name: self.__unsafe_private_named.2.unwrap(),
            source: self.__unsafe_private_named.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

/// Response type for
///sh.tangled.repo.forkSync
pub struct ForkSyncResponse;
impl jacquard_common::xrpc::XrpcResp for ForkSyncResponse {
    const NSID: &'static str = "sh.tangled.repo.forkSync";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for ForkSync<'a> {
    const NSID: &'static str = "sh.tangled.repo.forkSync";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = ForkSyncResponse;
}

/// Endpoint type for
///sh.tangled.repo.forkSync
pub struct ForkSyncRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ForkSyncRequest {
    const PATH: &'static str = "/xrpc/sh.tangled.repo.forkSync";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = ForkSync<'de>;
    type Response = ForkSyncResponse;
}