// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.tangled.repo.setDefaultBranch
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct SetDefaultBranch<'a> {
    #[serde(borrow)]
    pub default_branch: jacquard_common::CowStr<'a>,
    #[serde(borrow)]
    pub repo: jacquard_common::types::string::AtUri<'a>,
}

pub mod set_default_branch_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Repo;
        type DefaultBranch;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Repo = Unset;
        type DefaultBranch = Unset;
    }
    ///State transition - sets the `repo` field to Set
    pub struct SetRepo<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetRepo<S> {}
    impl<S: State> State for SetRepo<S> {
        type Repo = Set<members::repo>;
        type DefaultBranch = S::DefaultBranch;
    }
    ///State transition - sets the `default_branch` field to Set
    pub struct SetDefaultBranch<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDefaultBranch<S> {}
    impl<S: State> State for SetDefaultBranch<S> {
        type Repo = S::Repo;
        type DefaultBranch = Set<members::default_branch>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `repo` field
        pub struct repo(());
        ///Marker type for the `default_branch` field
        pub struct default_branch(());
    }
}

/// Builder for constructing an instance of this type
pub struct SetDefaultBranchBuilder<'a, S: set_default_branch_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> SetDefaultBranch<'a> {
    /// Create a new builder for this type
    pub fn new() -> SetDefaultBranchBuilder<'a, set_default_branch_state::Empty> {
        SetDefaultBranchBuilder::new()
    }
}

impl<'a> SetDefaultBranchBuilder<'a, set_default_branch_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        SetDefaultBranchBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> SetDefaultBranchBuilder<'a, S>
where
    S: set_default_branch_state::State,
    S::DefaultBranch: set_default_branch_state::IsUnset,
{
    /// Set the `defaultBranch` field (required)
    pub fn default_branch(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> SetDefaultBranchBuilder<'a, set_default_branch_state::SetDefaultBranch<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        SetDefaultBranchBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> SetDefaultBranchBuilder<'a, S>
where
    S: set_default_branch_state::State,
    S::Repo: set_default_branch_state::IsUnset,
{
    /// Set the `repo` field (required)
    pub fn repo(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> SetDefaultBranchBuilder<'a, set_default_branch_state::SetRepo<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        SetDefaultBranchBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> SetDefaultBranchBuilder<'a, S>
where
    S: set_default_branch_state::State,
    S::Repo: set_default_branch_state::IsSet,
    S::DefaultBranch: set_default_branch_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> SetDefaultBranch<'a> {
        SetDefaultBranch {
            default_branch: self.__unsafe_private_named.0.unwrap(),
            repo: self.__unsafe_private_named.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> SetDefaultBranch<'a> {
        SetDefaultBranch {
            default_branch: self.__unsafe_private_named.0.unwrap(),
            repo: self.__unsafe_private_named.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

/// Response type for
///sh.tangled.repo.setDefaultBranch
pub struct SetDefaultBranchResponse;
impl jacquard_common::xrpc::XrpcResp for SetDefaultBranchResponse {
    const NSID: &'static str = "sh.tangled.repo.setDefaultBranch";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for SetDefaultBranch<'a> {
    const NSID: &'static str = "sh.tangled.repo.setDefaultBranch";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = SetDefaultBranchResponse;
}

/// Endpoint type for
///sh.tangled.repo.setDefaultBranch
pub struct SetDefaultBranchRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SetDefaultBranchRequest {
    const PATH: &'static str = "/xrpc/sh.tangled.repo.setDefaultBranch";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = SetDefaultBranch<'de>;
    type Response = SetDefaultBranchResponse;
}