// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.tangled.pipeline.status
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct Status<'a> {
    /// time of creation of this status update
    pub created_at: jacquard_common::types::string::Datetime,
    /// error message if failed
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub error: Option<jacquard_common::CowStr<'a>>,
    /// exit code if failed
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub exit_code: Option<i64>,
    /// ATURI of the pipeline
    #[serde(borrow)]
    pub pipeline: jacquard_common::types::string::AtUri<'a>,
    /// status of the workflow
    #[serde(borrow)]
    pub status: jacquard_common::CowStr<'a>,
    /// name of the workflow within this pipeline
    #[serde(borrow)]
    pub workflow: jacquard_common::types::string::AtUri<'a>,
}

pub mod status_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Pipeline;
        type Workflow;
        type Status;
        type CreatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Pipeline = Unset;
        type Workflow = Unset;
        type Status = Unset;
        type CreatedAt = Unset;
    }
    ///State transition - sets the `pipeline` field to Set
    pub struct SetPipeline<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetPipeline<S> {}
    impl<S: State> State for SetPipeline<S> {
        type Pipeline = Set<members::pipeline>;
        type Workflow = S::Workflow;
        type Status = S::Status;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `workflow` field to Set
    pub struct SetWorkflow<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetWorkflow<S> {}
    impl<S: State> State for SetWorkflow<S> {
        type Pipeline = S::Pipeline;
        type Workflow = Set<members::workflow>;
        type Status = S::Status;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `status` field to Set
    pub struct SetStatus<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetStatus<S> {}
    impl<S: State> State for SetStatus<S> {
        type Pipeline = S::Pipeline;
        type Workflow = S::Workflow;
        type Status = Set<members::status>;
        type CreatedAt = S::CreatedAt;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Pipeline = S::Pipeline;
        type Workflow = S::Workflow;
        type Status = S::Status;
        type CreatedAt = Set<members::created_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `pipeline` field
        pub struct pipeline(());
        ///Marker type for the `workflow` field
        pub struct workflow(());
        ///Marker type for the `status` field
        pub struct status(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
    }
}

/// Builder for constructing an instance of this type
pub struct StatusBuilder<'a, S: status_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Status<'a> {
    /// Create a new builder for this type
    pub fn new() -> StatusBuilder<'a, status_state::Empty> {
        StatusBuilder::new()
    }
}

impl<'a> StatusBuilder<'a, status_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        StatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> StatusBuilder<'a, S>
where
    S: status_state::State,
    S::CreatedAt: status_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<jacquard_common::types::string::Datetime>,
    ) -> StatusBuilder<'a, status_state::SetCreatedAt<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        StatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: status_state::State> StatusBuilder<'a, S> {
    /// Set the `error` field (optional)
    pub fn error(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `error` field to an Option value (optional)
    pub fn maybe_error(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S: status_state::State> StatusBuilder<'a, S> {
    /// Set the `exitCode` field (optional)
    pub fn exit_code(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `exitCode` field to an Option value (optional)
    pub fn maybe_exit_code(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S> StatusBuilder<'a, S>
where
    S: status_state::State,
    S::Pipeline: status_state::IsUnset,
{
    /// Set the `pipeline` field (required)
    pub fn pipeline(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> StatusBuilder<'a, status_state::SetPipeline<S>> {
        self.__unsafe_private_named.3 = ::core::option::Option::Some(value.into());
        StatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> StatusBuilder<'a, S>
where
    S: status_state::State,
    S::Status: status_state::IsUnset,
{
    /// Set the `status` field (required)
    pub fn status(
        mut self,
        value: impl Into<jacquard_common::CowStr<'a>>,
    ) -> StatusBuilder<'a, status_state::SetStatus<S>> {
        self.__unsafe_private_named.4 = ::core::option::Option::Some(value.into());
        StatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> StatusBuilder<'a, S>
where
    S: status_state::State,
    S::Workflow: status_state::IsUnset,
{
    /// Set the `workflow` field (required)
    pub fn workflow(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> StatusBuilder<'a, status_state::SetWorkflow<S>> {
        self.__unsafe_private_named.5 = ::core::option::Option::Some(value.into());
        StatusBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> StatusBuilder<'a, S>
where
    S: status_state::State,
    S::Pipeline: status_state::IsSet,
    S::Workflow: status_state::IsSet,
    S::Status: status_state::IsSet,
    S::CreatedAt: status_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Status<'a> {
        Status {
            created_at: self.__unsafe_private_named.0.unwrap(),
            error: self.__unsafe_private_named.1,
            exit_code: self.__unsafe_private_named.2,
            pipeline: self.__unsafe_private_named.3.unwrap(),
            status: self.__unsafe_private_named.4.unwrap(),
            workflow: self.__unsafe_private_named.5.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Status<'a> {
        Status {
            created_at: self.__unsafe_private_named.0.unwrap(),
            error: self.__unsafe_private_named.1,
            exit_code: self.__unsafe_private_named.2,
            pipeline: self.__unsafe_private_named.3.unwrap(),
            status: self.__unsafe_private_named.4.unwrap(),
            workflow: self.__unsafe_private_named.5.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> Status<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, StatusRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct StatusGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: Status<'a>,
}

impl From<StatusGetRecordOutput<'_>> for Status<'_> {
    fn from(output: StatusGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for Status<'_> {
    const NSID: &'static str = "sh.tangled.pipeline.status";
    type Record = StatusRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct StatusRecord;
impl jacquard_common::xrpc::XrpcResp for StatusRecord {
    const NSID: &'static str = "sh.tangled.pipeline.status";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = StatusGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for StatusRecord {
    const NSID: &'static str = "sh.tangled.pipeline.status";
    type Record = StatusRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Status<'a> {
    fn nsid() -> &'static str {
        "sh.tangled.pipeline.status"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_sh_tangled_pipeline_status()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_sh_tangled_pipeline_status() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("sh.tangled.pipeline.status"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                    description: None,
                    key: Some(::jacquard_common::CowStr::new_static("tid")),
                    record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                        description: None,
                        required: Some(
                            vec![
                                ::jacquard_common::smol_str::SmolStr::new_static("pipeline"),
                                ::jacquard_common::smol_str::SmolStr::new_static("workflow"),
                                ::jacquard_common::smol_str::SmolStr::new_static("status"),
                                ::jacquard_common::smol_str::SmolStr::new_static("createdAt")
                            ],
                        ),
                        nullable: None,
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = ::std::collections::BTreeMap::new();
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "createdAt",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "time of creation of this status update",
                                        ),
                                    ),
                                    format: Some(
                                        ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                    ),
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("error"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "error message if failed",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "exitCode",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Integer(::jacquard_lexicon::lexicon::LexInteger {
                                    description: None,
                                    default: None,
                                    minimum: None,
                                    maximum: None,
                                    r#enum: None,
                                    r#const: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "pipeline",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "ATURI of the pipeline",
                                        ),
                                    ),
                                    format: Some(
                                        ::jacquard_lexicon::lexicon::LexStringFormat::AtUri,
                                    ),
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("status"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "status of the workflow",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "workflow",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "name of the workflow within this pipeline",
                                        ),
                                    ),
                                    format: Some(
                                        ::jacquard_lexicon::lexicon::LexStringFormat::AtUri,
                                    ),
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map
                        },
                    }),
                }),
            );
            map
        },
    }
}